
removable = [
	"JOB DESCRIPTION",
	"PURPOSE OF THE JOB",
	"Job Context",
	"Challenges",
	"DETAILS OF THE JOB",
	"Designation & Job",
	"Level",
	"Business Unit",
	"Function",
	"Country",
	"Work Location",
	"Reporting Manager",
	"Manager’s Manager",
	"Matrix Manager",
	"Team Size",
	"Direct Reportees",
	"KEY ACCOUNTABILITIES",
	"Training & Development",
	"KEY INTERFACES",
	"EDUCATION & EXPERIENCE",
	"Desired Certifications",
	"Experience Range",
	"Desirable experience",
	"SKILLS REQUIRED",
	"Skills",
	"Description",
	"Behavioral Skills"
]